### ISSUE TITLE
issue when installing

### ISSUE THREAD

**Issue by pierreg14** [thags/lingqAnkiSync#23]
Hi, when I try to install the addon and I restart it, it shows me this message :

"Traceback (most recent call last):
  File "aqt/addons.py", line 230, in loadAddons
  File "/Users/pierreg/Library/Application Support/Anki2/addons21/594879777/__init__.py", line 1, in <module>
    from .popUpWindow import UI
  File "/Users/pierreg/Library/Application Support/Anki2/addons21/594879777/popUpWindow.py", line 6, in <module>
    from .UIActionHandler import ActionHandler
  File "/Users/pierreg/Library/Application Support/Anki2/addons21/594879777/UIActionHandler.py", line 1, in <module>
    from .Converter import ConvertAnkiCardsToLingqs, ConvertLingqsToAnkiCards
  File "/Users/pierreg/Library/Application Support/Anki2/addons21/594879777/Converter.py", line 7, in <module>
    def ConvertAnkiCardsToLingqs(ankiCards: list[AnkiCard], statusToInterval: dict[int:int]) -> list[Lingq]:
TypeError: 'type' object is not subscriptable"

mac OS Big sur 11.7.4
Anki version : 2.1.49
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

On the anki addon link --> Supported Anki versions: 2.1.6-2.1.16+ (Updated 2023-03-20)

Thanks.

**Comment by thags** [comment]
Thanks for sending this in. I'll add this in to the code as long as it doesn't cause any issues on the windows side. I don't have a mac to test with.
