### ISSUE TITLE
BUG: Import from LINQ seems to be broken.

### ISSUE THREAD

**Issue by not-night-but** [thags/lingqAnkiSync#36]
### Steps to reproduce 
1. Menu Tools -> Import LingQs
2. Immediate error pops up

![image](https://github.com/thags/lingqAnkiSync/assets/58712803/4d1dc141-1441-4008-884e-aafb6b03b1b7)

Seems like this might be a regression related to the upgrade to pyqt 6?

Debug Log:
```
Anki 23.12.1 (1a1d4d54) (src) (ao)
Python 3.11.8 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.8.2-zen1-1-zen-x86_64-with-glibc2.39

Traceback (most recent call last):
  File "/home/notnight/.local/share/Anki2/addons21/594879777/popUpWindow.py", line 93, in <lambda>
    action.triggered.connect(lambda: UI().run())
                                     ^^^^
  File "/home/notnight/.local/share/Anki2/addons21/594879777/popUpWindow.py", line 19, in __init__
    QPushButton("Import"), QDialogButtonBox.AcceptRole)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QDialogButtonBox' has no attribute 'AcceptRole'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Lingq Anki Sync ['594879777', 2023-12-25T14:25, 'None', '']
More Overview Stats 21 ['738807903', 2021-07-30T13:13, 'None', '']
PassFail 2 Remove the Easy and Hard buttons ['876946123', 2023-01-23T18:59, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T19:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1771074083 594879777 738807903 876946123

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
```

**Comment by not-night-but** [comment]
Looking at the code now, it seems like this may have been fixed, just not yet deployed to AnkiWeb?

**Comment by tavisjd** [comment]
Swapping out the files, this does appear to be fixed?

**Comment by thags** [comment]
This is fixed but was not deployed, there is an issue with the build. Fixing that now and then will deploy to ankiweb

**Comment by thags** [comment]
This has been fixed. The anki addon page has been updated with the new version. I tested as working with latest version of Anki on mac.
